/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AppRouteImport } from "./routes/app";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppIndexRouteImport } from "./routes/app.index";
import { Route as AppDbProfilesRouteImport } from "./routes/app.db-profiles";
import { Route as AppChatsChatIdRouteImport } from "./routes/app.chats.$chatId";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any);
const AppDbProfilesRoute = AppDbProfilesRouteImport.update({
  id: "/db-profiles",
  path: "/db-profiles",
  getParentRoute: () => AppRoute,
} as any);
const AppChatsChatIdRoute = AppChatsChatIdRouteImport.update({
  id: "/chats/$chatId",
  path: "/chats/$chatId",
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/app": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/app/db-profiles": typeof AppDbProfilesRoute;
  "/app/": typeof AppIndexRoute;
  "/app/chats/$chatId": typeof AppChatsChatIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/app/db-profiles": typeof AppDbProfilesRoute;
  "/app": typeof AppIndexRoute;
  "/app/chats/$chatId": typeof AppChatsChatIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/app": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/app/db-profiles": typeof AppDbProfilesRoute;
  "/app/": typeof AppIndexRoute;
  "/app/chats/$chatId": typeof AppChatsChatIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/app" | "/login" | "/app/db-profiles" | "/app/" | "/app/chats/$chatId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/app/db-profiles" | "/app" | "/app/chats/$chatId";
  id: "__root__" | "/" | "/app" | "/login" | "/app/db-profiles" | "/app/" | "/app/chats/$chatId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/": {
      id: "/app/";
      path: "/";
      fullPath: "/app/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/db-profiles": {
      id: "/app/db-profiles";
      path: "/db-profiles";
      fullPath: "/app/db-profiles";
      preLoaderRoute: typeof AppDbProfilesRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/app/chats/$chatId": {
      id: "/app/chats/$chatId";
      path: "/chats/$chatId";
      fullPath: "/app/chats/$chatId";
      preLoaderRoute: typeof AppChatsChatIdRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppDbProfilesRoute: typeof AppDbProfilesRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppChatsChatIdRoute: typeof AppChatsChatIdRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppDbProfilesRoute: AppDbProfilesRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatsChatIdRoute: AppChatsChatIdRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
